# Find eligible builder and runner images on Docker Hub. We use Ubuntu/Debian
# instead of Alpine to avoid DNS resolution issues in production.
#
# https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=ubuntu
# https://hub.docker.com/_/ubuntu?tab=tags
#
# This file is based on these images:
#
#   - https://hub.docker.com/r/hexpm/elixir/tags - for the build image
#   - https://hub.docker.com/_/debian?tab=tags&page=1&name=bullseye-20230612-slim - for the release image
#   - https://pkgs.org/ - resource for finding needed packages
#   - Ex: hexpm/elixir:1.14.5-erlang-25.3.2.4-debian-bullseye-20230612-slim
#
ARG ELIXIR_VERSION=1.14.5
ARG OTP_VERSION=25.3.2.4
ARG DEBIAN_VERSION=bullseye-20230612-slim

ARG IMAGE="docker.io/hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

FROM ${IMAGE} 

# install dependencies
RUN apt-get update -y && \
  apt-get install -y libstdc++6 build-essential openssl libncurses5 locales ca-certificates git postgresql-client \
  && apt-get clean && rm -f /var/lib/apt/lists/*_*

# set build ENV
ENV MIX_ENV="dev"

EXPOSE 4000

WORKDIR /workspace

# Set the default entrypoint to run the Phoenix server in development
COPY ./entrypoint.dev.sh /workspace/entrypoint.dev.sh
RUN chmod +x /workspace/entrypoint.dev.sh

ENTRYPOINT ["/workspace/entrypoint.dev.sh"]

